/**
 * VFO-15: ZIP decompression-bomb guard for Office/ODF documents.
 */

import { describe, test, expect, beforeAll, afterAll } from "@jest/globals";
import { promises as fs } from "fs";
import path from "path";
import os from "os";
import zlib from "zlib";
import { Document, Packer, Paragraph } from "docx";
import { assertSafeZipFile, UnsafeZipError } from "../utils/zip-guard.js";
import { parseDocument, DocumentParseError } from "../utils/document-parser.js";

const WORKSPACE = path.join(
  os.tmpdir(),
  `vulcan-test-zip-guard-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`
);

interface RawEntry {
  name: string;
  /** Bytes stored in the archive (already compressed for method 8). */
  stored: Buffer;
  method?: number;
  /** Declared uncompressed size (defaults to the real one). */
  uncompressedSize?: number;
  /** Override the declared compressed size (defaults to stored.length). */
  compressedSize?: number;
}

/** Build a ZIP archive by hand so headers can lie. */
function buildZip(
  entries: RawEntry[],
  opts: { totalEntries?: number; zip64Locator?: boolean } = {}
): Buffer {
  const locals: Buffer[] = [];
  const centrals: Buffer[] = [];
  let offset = 0;
  for (const e of entries) {
    const method = e.method ?? 8;
    const name = Buffer.from(e.name, "utf8");
    const real =
      method === 8 ? zlib.inflateRawSync(e.stored).length : e.stored.length;
    const uncompressed = e.uncompressedSize ?? real;
    const compressed = e.compressedSize ?? e.stored.length;

    const local = Buffer.alloc(30);
    local.writeUInt32LE(0x04034b50, 0);
    local.writeUInt16LE(20, 4);
    local.writeUInt16LE(method, 8);
    local.writeUInt32LE(compressed, 18);
    local.writeUInt32LE(uncompressed, 22);
    local.writeUInt16LE(name.length, 26);
    locals.push(local, name, e.stored);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(0x02014b50, 0);
    central.writeUInt16LE(20, 4);
    central.writeUInt16LE(20, 6);
    central.writeUInt16LE(method, 10);
    central.writeUInt32LE(compressed, 20);
    central.writeUInt32LE(uncompressed, 24);
    central.writeUInt16LE(name.length, 28);
    central.writeUInt32LE(offset, 42);
    centrals.push(central, name);

    offset += 30 + name.length + e.stored.length;
  }
  const cd = Buffer.concat(centrals);
  const parts = [...locals, cd];
  if (opts.zip64Locator) {
    const locator = Buffer.alloc(20);
    locator.writeUInt32LE(0x07064b50, 0);
    parts.push(locator);
  }
  const eocd = Buffer.alloc(22);
  eocd.writeUInt32LE(0x06054b50, 0);
  const count = opts.totalEntries ?? entries.length;
  eocd.writeUInt16LE(count, 8);
  eocd.writeUInt16LE(count, 10);
  eocd.writeUInt32LE(cd.length, 12);
  eocd.writeUInt32LE(offset, 16);
  parts.push(eocd);
  return Buffer.concat(parts);
}

async function writeFixture(name: string, data: Buffer): Promise<string> {
  const p = path.join(WORKSPACE, name);
  await fs.writeFile(p, data);
  return p;
}

describe("zip-guard", () => {
  let legitDocx: string;

  beforeAll(async () => {
    await fs.mkdir(WORKSPACE, { recursive: true });
    const doc = new Document({
      sections: [
        {
          children: [
            new Paragraph("Zip guard legit document"),
            new Paragraph("Second paragraph"),
          ],
        },
      ],
    });
    legitDocx = await writeFixture("legit.docx", await Packer.toBuffer(doc));
  });

  afterAll(async () => {
    await fs.rm(WORKSPACE, { recursive: true, force: true });
  });

  test("accepts a legitimate DOCX generated by the docx package", async () => {
    const result = await assertSafeZipFile(legitDocx);
    expect(result.entries.length).toBeGreaterThan(3);
    expect(result.totalUncompressedBytes).toBeGreaterThan(0);
  });

  test("legitimate DOCX still parses", async () => {
    const parsed = await parseDocument(legitDocx);
    expect(parsed.text).toContain("Zip guard legit document");
  });

  test("accepts a small hand-built archive (stored and deflated)", async () => {
    const p = await writeFixture(
      "small.docx",
      buildZip([
        { name: "a.txt", stored: Buffer.from("hello"), method: 0 },
        { name: "b.txt", stored: zlib.deflateRawSync(Buffer.alloc(1000, 65)) },
      ])
    );
    await expect(assertSafeZipFile(p)).resolves.toBeDefined();
  });

  test("rejects a central directory claiming a huge total uncompressed size", async () => {
    // 21 entries x 10 MB declared (each exempt from the ratio check).
    const stored = zlib.deflateRawSync(Buffer.from("x"));
    const p = await writeFixture(
      "huge-claim.docx",
      buildZip(
        Array.from({ length: 21 }, (_, i) => ({
          name: `word/part${i}.xml`,
          stored,
          uncompressedSize: 10 * 1024 * 1024,
        }))
      )
    );
    const err = await assertSafeZipFile(p).catch((e) => e);
    expect(err).toBeInstanceOf(UnsafeZipError);
    expect(err.reason).toBe("limit");
    expect(err.message).toMatch(/total uncompressed size exceeds 200\.0 MB/);
  });

  test("rejects an entry with an excessive compression ratio", async () => {
    const stored = zlib.deflateRawSync(Buffer.from("x"));
    const p = await writeFixture(
      "ratio.docx",
      buildZip([
        {
          name: "word/document.xml",
          stored,
          uncompressedSize: 20 * 1024 * 1024,
          compressedSize: stored.length,
        },
      ])
    );
    await expect(assertSafeZipFile(p)).rejects.toThrow(/compression ratio/);
  });

  test("rejects an entry that inflates beyond its declared size", async () => {
    // Real zip-bomb shape: 4 MB of zeros declared as 1 KB.
    const stored = zlib.deflateRawSync(Buffer.alloc(4 * 1024 * 1024));
    const p = await writeFixture(
      "lying.docx",
      buildZip([{ name: "word/document.xml", stored, uncompressedSize: 1024 }])
    );
    await expect(assertSafeZipFile(p)).rejects.toThrow(
      /inflates beyond its declared size/
    );
  });

  test("rejects archives with too many entries", async () => {
    const p = await writeFixture(
      "many.docx",
      buildZip([{ name: "a", stored: Buffer.from("a"), method: 0 }], {
        totalEntries: 10_001,
      })
    );
    await expect(assertSafeZipFile(p)).rejects.toThrow(/10001 entries/);
  });

  test("counts central directory records, not just the declared count", async () => {
    const entries = Array.from({ length: 5 }, (_, i) => ({
      name: `f${i}`,
      stored: Buffer.from("a"),
      method: 0,
    }));
    const p = await writeFixture("count.docx", buildZip(entries, { totalEntries: 2 }));
    const err = await assertSafeZipFile(p).catch((e) => e);
    expect(err).toBeInstanceOf(UnsafeZipError);
    expect(err.reason).toBe("invalid");
  });

  test("rejects ZIP64 markers in the end record", async () => {
    const p = await writeFixture(
      "zip64-eocd.docx",
      buildZip([{ name: "a", stored: Buffer.from("a"), method: 0 }], {
        totalEntries: 0xffff,
      })
    );
    const err = await assertSafeZipFile(p).catch((e) => e);
    expect(err.reason).toBe("unsupported");
    expect(err.message).toMatch(/ZIP64/);
  });

  test("rejects ZIP64 end-of-central-directory locator", async () => {
    const p = await writeFixture(
      "zip64-locator.docx",
      buildZip([{ name: "a", stored: Buffer.from("a"), method: 0 }], {
        zip64Locator: true,
      })
    );
    await expect(assertSafeZipFile(p)).rejects.toThrow(/ZIP64/);
  });

  test("rejects ZIP64 sizes in a central directory entry", async () => {
    const p = await writeFixture(
      "zip64-entry.docx",
      buildZip([
        {
          name: "a",
          stored: zlib.deflateRawSync(Buffer.from("a")),
          uncompressedSize: 0xffffffff,
        },
      ])
    );
    await expect(assertSafeZipFile(p)).rejects.toThrow(/ZIP64/);
  });

  test("rejects files that are not ZIP archives", async () => {
    const p = await writeFixture("not-a-zip.docx", Buffer.from("just some text"));
    const err = await assertSafeZipFile(p).catch((e) => e);
    expect(err.reason).toBe("invalid");
  });

  test("parseDocument refuses a zip bomb before any parser runs", async () => {
    const stored = zlib.deflateRawSync(Buffer.alloc(4 * 1024 * 1024));
    const p = await writeFixture(
      "bomb.xlsx",
      buildZip([{ name: "xl/workbook.xml", stored, uncompressedSize: 100 }])
    );
    const err = await parseDocument(p).catch((e) => e);
    expect(err).toBeInstanceOf(DocumentParseError);
    expect(err.message).toMatch(/^Refusing to parse XLSX document: .*possible zip bomb/);
  });

  test("parseDocument reports non-ZIP office files as corrupted", async () => {
    const p = await writeFixture("garbage.odt", Buffer.from("not a zip at all"));
    await expect(parseDocument(p)).rejects.toThrow(
      /corrupted or is not a valid ODT document/
    );
  });
});
